const pottingComponents = Object.freeze({
  "plantBased (organic)": [
    "Banana peel compost",
    "Biochar",
    "Coco coir",
    "Coconut fiber",
    "Coconut husk chips",
    "Coffee grounds",
    "Composted bark",
    "Cotton burr compost",
    "Fir bark",
    "Fruit and vegetable compost",
    "Ground sunflower stalks",
    "Hemp fiber",
    "Kitchen waste compost",
    "Leaf mold",
    "Long-fiber sphagnum moss",
    "Mulch",
    "Orchid bark",
    "Organic cane mulch",
    "Paper pulp (sterilized)",
    "Peat moss",
    "Pine bark",
    "Plant-based compost",
    "Rice hulls",
    "Shredded leaves",
    "Shredded paper",
    "Sphagnum moss",
    "Tea leaves",
    "Tree fern fiber",
    "Wood chips",
  ],
  "animalBased (organic)": [
    "Bat guano",
    "Blood meal",
    "Bone meal",
    "Cow manure",
    "Crustacean meal",
    "Fish hydrolysate",
    "Vermicompost",
    "Worm castings",
  ],
  "microbialBased (organic)": [
    "Composted forest humus (from decayed wood/leaves)",
    "Mushroom compost (low-salt, partially organic)",
    "Mycorrhizal fungi inoculant",
    "Trichoderma fungi",
  ],
  inorganic: [
    "Akadama",
    "Coarse sand",
    "Clay pebbles / LECA",
    "Diatomaceous earth",
    "Gravel",
    "Kanuma",
    "Lava rock",
    "Perlite",
    "Pumice",
    "Seramis",
    "Silica sand",
    "Vermiculite",
    "Zeolite",
  ],
  mix: [
    "Airy potting mix",
    "Alocasia mix",
    "Anthurium mix",
    "Aroid mix",
    "Begonia mix",
    "Bonsai mix",
    "Bromeliad mix",
    "Cactus mix",
    "Calathea mix",
    "Chunky indoor mix",
    "Fern mix",
    "High-drainage mix",
    "Houseplant tropical mix",
    "Hoya mix",
    "Lechuza-PON",
    "Minimal substrate mix",
    "Moisture-retentive mix",
    "Monstera mix",
    "Orchid mix",
    "Peperomia mix",
    "Philodendron mix",
    "PON-style mix",
    "Pothos mix",
    "Propagation mix",
    "Rooting mix",
    "Seed starting mix",
    "Self-watering mix",
    "Semi-hydroponic mix",
    "Soilless mix",
    "Succulent mix",
    "Syngonium mix",
  ],
});

export default pottingComponents;
