import Collection from "./Collection";

const samplePlants = [
  {
    id: "1",
    commonName: "Monstera Deliciosa",
    species: "Mpnstera deliciosa",
    genus: "Monstera deliciosa",
    nickname: "Monty",
    description:
      "My favorite plant! Got it from a local nursery and it's been thriving ever since.",
    roomLocation: "Living Room",
    isPetSafe: true,
    isHealthy: false,
    windowDirection: "east-facing-northern-hemisphere",
    isBlooming: true,
    isAirCleaning: true,
    ownedSince: new Date("2022-03-15"),
    lastRepotted: new Date("2023-05-10"),
    soilType: "Soil",
    pottingMix: ["Indoor Plant Mix", "Perlite", "Orchid Bark"],
    pictures: [
      { url: "/assets/monstera-1.webp" },
      // { url: "/assets/monstera-2.png" },
    ],
  },
  {
    id: "2",
    commonName: "Snake Plant",
    species: "trifasciata",
    genus: "Sansevieria",
    nickname: "Snakey",
    description: "Very low maintenance plant that purifies the air.",
    roomLocation: "Bedroom",
    isPetSafe: false,
    isHealthy: true,
    windowDirection: "north-facing-northern-hemisphere",
    isBlooming: false,
    isAirCleaning: true,
    ownedSince: new Date("2021-07-22"),
    lastRepotted: new Date("2022-08-15"),
    soilType: "Soil",
    pottingMix: ["Succulent Mix", "Sand"],
    pictures: [
      { url: "/assets/snake-plant-1.avif" },
      { url: "/assets/snake-plant-2.webp" },
      { url: "/assets/snake-plant-3.jpg" },
    ],
  },
  {
    id: "3",
    commonName: "Peace Lily",
    species: "wallisii",
    genus: "Spathiphyllum",
    nickname: "Peaceful Patty",
    description:
      "Droops when it needs water, but perks right back up after watering.",
    roomLocation: "Office",
    isPetSafe: true,
    isHealthy: false,
    windowDirection: "west-facing-northern-hemisphere",
    isBlooming: true,
    isAirCleaning: true,
    ownedSince: new Date("2023-01-10"),
    soilType: "Soil",
    pottingMix: ["All-Purpose Potting Mix", "Peat Moss"],
    pictures: [
      // { url: "/assets/peace-lily-1.jpg" },
      // { url: "/assets/peace-lily-2.webp" },
    ],
  },
  {
    id: "4",
    commonName: "Pothos",
    species: "aureum",
    genus: "Epipremnum",
    nickname: "Hanging Harry",
    description: "Fast growing vine that's perfect for hanging baskets.",
    roomLocation: "Kitchen",
    isPetSafe: false,
    isHealthy: true,
    windowDirection: "south-facing-northern-hemisphere",
    isBlooming: false,
    isAirCleaning: true,
    ownedSince: new Date("2022-09-05"),
    lastRepotted: new Date("2023-04-20"),
    soilType: "Soil",
    pottingMix: ["Indoor Plant Mix", "Perlite"],
    pictures: [
      { url: "/assets/pothos-1.webp" },
      { url: "/assets/pothos-2.jpg" },
      { url: "/assets/pothos-3.avif" },
      { url: "/assets/pothos-4.jpg" },
    ],
  },
  {
    id: "5",
    commonName: "Spider Plant",
    species: "comosum",
    genus: "Chlorophytum",
    nickname: "Charlotte",
    description: "Produces lots of babies that can be propagated easily.",
    roomLocation: "Bathroom",
    isPetSafe: true,
    isHealthy: true,
    windowDirection: "east-facing-northern-hemisphere",
    isBlooming: false,
    isAirCleaning: true,
    ownedSince: new Date("2023-04-18"),
    soilType: "Soil",
    pottingMix: ["All-Purpose Potting Mix"],
    pictures: [
      { url: "/assets/spider-plant-1.jpg" },
      { url: "/assets/spider-plant-2.webp" },
      { url: "/assets/spider-plant-3.webp" },
    ],
  },
  {
    id: "6",
    commonName: "Fiddle Leaf Fig",
    species: "lyrata",
    genus: "Ficus",
    nickname: "Figgy",
    description: "Temperamental but beautiful statement plant.",
    roomLocation: "Living Room",
    isPetSafe: false,
    isHealthy: true,
    windowDirection: "south-facing-northern-hemisphere",
    isBlooming: false,
    isAirCleaning: false,
    ownedSince: new Date("2021-11-30"),
    lastRepotted: new Date("2022-06-15"),
    soilType: "Soil",
    pottingMix: ["Indoor Plant Mix", "Perlite", "Compost"],
    pictures: [
      { url: "/assets/fiddle-leaf-fig-1.webp" },
      { url: "/assets/fiddle-leaf-fig-2.jpg" },
      { url: "/assets/fiddle-leaf-fig-3.webp" },
    ],
  },
];

export default function Home() {
  return (
    <main className="container py-8 px-6 mx-auto max-w-7xl">
      <Collection plants={samplePlants} />
    </main>
  );
}
