import { GrowingMediumEnum, WindowDirectionEnum } from "@/lib/data/plantDetailsTypes";
import Collection from "./Collection";
import { AddPlantForm } from "@/app/add-plant/schema";

const samplePlants: AddPlantForm[] = [
  {
    commonName: "Monstera Deliciosa",
    species: "Mpnstera deliciosa",
    genus: "Monstera deliciosa",
    nickname: "Monty",
    source: undefined,
    ownedSince: new Date("2022-03-15"),
    isSafe: true,
    isAirPurifying: true,
    description:
      "My favorite plant! Got it from a local nursery and it's been thriving ever since.",
    currentHeight: undefined,
    currentPotSize: undefined,
    lastRepotted: new Date("2023-05-10"),
    humidity: undefined,
    temperature: undefined,
    roomLocation: "Living Room",
    windowDirection: WindowDirectionEnum.EastFacingNorthernHemisphere,
    lightExposure: undefined,
    growingMedium: GrowingMediumEnum.Soil,
    pottingMix: ["Indoor Plant Mix", "Perlite", "Orchid Bark"],
    wateringNotes: undefined,
    mistingNotes: undefined,
    leafCleaningNotes: undefined,
    fertilizingNotes: undefined,
    additionalNotes: undefined,
  },
  {
    commonName: "Snake Plant",
    species: "trifasciata",
    genus: "Sansevieria",
    nickname: "Snakey",
    source: undefined,
    ownedSince: new Date("2021-07-22"),
    isSafe: false,
    isAirPurifying: true,
    description: "Very low maintenance plant that purifies the air.",
    currentHeight: undefined,
    currentPotSize: undefined,
    lastRepotted: new Date("2022-08-15"),
    humidity: undefined,
    temperature: undefined,
    roomLocation: "Bedroom",
    windowDirection: WindowDirectionEnum.NorthFacingNorthernHemisphere,
    lightExposure: undefined,
    growingMedium: GrowingMediumEnum.Soil,
    pottingMix: ["Succulent Mix", "Sand"],
    wateringNotes: undefined,
    mistingNotes: undefined,
    leafCleaningNotes: undefined,
    fertilizingNotes: undefined,
    additionalNotes: undefined,
  },
  {
    commonName: "Peace Lily",
    species: "wallisii",
    genus: "Spathiphyllum",
    nickname: "Peaceful Patty",
    source: undefined,
    ownedSince: new Date("2023-01-10"),
    isSafe: true,
    isAirPurifying: true,
    description:
      "Droops when it needs water, but perks right back up after watering.",
    currentHeight: undefined,
    currentPotSize: undefined,
    lastRepotted: undefined,
    humidity: undefined,
    temperature: undefined,
    roomLocation: "Office",
    windowDirection: WindowDirectionEnum.WestFacingNorthernHemisphere,
    lightExposure: undefined,
    growingMedium: GrowingMediumEnum.Soil,
    pottingMix: ["All-Purpose Potting Mix", "Peat Moss"],
    wateringNotes: undefined,
    mistingNotes: undefined,
    leafCleaningNotes: undefined,
    fertilizingNotes: undefined,
    additionalNotes: undefined,
  },
  {
    commonName: "Pothos",
    species: "aureum",
    genus: "Epipremnum",
    nickname: "Hanging Harry",
    source: undefined,
    ownedSince: new Date("2022-09-05"),
    isSafe: false,
    isAirPurifying: true,
    description: "Fast growing vine that's perfect for hanging baskets.",
    currentHeight: undefined,
    currentPotSize: undefined,
    lastRepotted: new Date("2023-04-20"),
    humidity: undefined,
    temperature: undefined,
    roomLocation: "Kitchen",
    windowDirection: WindowDirectionEnum.SouthFacingNorthernHemisphere,
    lightExposure: undefined,
    growingMedium: GrowingMediumEnum.Soil,
    pottingMix: ["Indoor Plant Mix", "Perlite"],
    wateringNotes: undefined,
    mistingNotes: undefined,
    leafCleaningNotes: undefined,
    fertilizingNotes: undefined,
    additionalNotes: undefined,
  },
  {
    commonName: "Spider Plant",
    species: "comosum",
    genus: "Chlorophytum",
    nickname: "Charlotte",
    source: undefined,
    ownedSince: new Date("2023-04-18"),
    isSafe: true,
    isAirPurifying: true,
    description: "Produces lots of babies that can be propagated easily.",
    currentHeight: undefined,
    currentPotSize: undefined,
    lastRepotted: undefined,
    humidity: undefined,
    temperature: undefined,
    roomLocation: "Bathroom",
    windowDirection: WindowDirectionEnum.EastFacingNorthernHemisphere,
    lightExposure: undefined,
    growingMedium: GrowingMediumEnum.Soil,
    pottingMix: ["All-Purpose Potting Mix"],
    wateringNotes: undefined,
    mistingNotes: undefined,
    leafCleaningNotes: undefined,
    fertilizingNotes: undefined,
    additionalNotes: undefined,
  },
  {
    commonName: "Fiddle Leaf Fig",
    species: "lyrata",
    genus: "Ficus",
    nickname: "Figgy",
    source: undefined,
    ownedSince: new Date("2021-11-30"),
    isSafe: false,
    isAirPurifying: false,
    description: "Temperamental but beautiful statement plant.",
    currentHeight: undefined,
    currentPotSize: undefined,
    lastRepotted: new Date("2022-06-15"),
    humidity: undefined,
    temperature: undefined,
    roomLocation: "Living Room",
    windowDirection: WindowDirectionEnum.SouthFacingNorthernHemisphere,
    lightExposure: undefined,
    growingMedium: GrowingMediumEnum.Soil,
    pottingMix: ["Indoor Plant Mix", "Perlite", "Compost"],
    wateringNotes: undefined,
    mistingNotes: undefined,
    leafCleaningNotes: undefined,
    fertilizingNotes: undefined,
    additionalNotes: undefined,
  },
];

export default function Home() {
  return (
    <main className="container py-8 px-6 mx-auto max-w-7xl">
      <Collection plants={samplePlants} />
    </main>
  );
}
